export interface NameInfo {
    name: string
    meaning: string
    cultural_notes: string
}

export const nameData: Record<'male' | 'female', NameInfo[]> = {
    male: [
        { name: 'Ethan', meaning: 'Strong, enduring', cultural_notes: 'Easy to pronounce in Mandarin' },
        { name: 'Lucas', meaning: 'Light, illumination', cultural_notes: 'Similar sound to Chinese name "Lu"' },
        { name: 'William', meaning: 'Strong-willed protector', cultural_notes: 'Classic name with good reputation' },
        { name: 'Noah', meaning: 'Rest, comfort', cultural_notes: 'Biblical name with global recognition' },
        { name: 'Liam', meaning: 'Strong-willed warrior', cultural_notes: 'Short and easy to pronounce internationally' },
        { name: 'Benjamin', meaning: 'Son of the right hand', cultural_notes: 'Versatile with nickname options like Ben' },
        { name: 'James', meaning: 'Supplanter', cultural_notes: 'Traditional name with business-like connotations' },
        { name: 'Alexander', meaning: 'Defender of mankind', cultural_notes: 'Has variations in many languages' },
        { name: 'Mason', meaning: 'Stone worker', cultural_notes: 'Modern name with professional sound' },
        { name: 'Daniel', meaning: 'God is my judge', cultural_notes: 'Biblical name recognized across cultures' },
        { name: 'Henry', meaning: 'Ruler of the home', cultural_notes: 'Royal associations and growing popularity' },
        { name: 'Jackson', meaning: 'Son of Jack', cultural_notes: 'Strong sound with nickname Jack' },
        { name: 'Sebastian', meaning: 'Revered, venerable', cultural_notes: 'Works well in multiple languages' },
        { name: 'Aiden', meaning: 'Little fire', cultural_notes: 'Modern name with Celtic roots' },
        { name: 'Matthew', meaning: 'Gift of God', cultural_notes: 'Biblical name with professional image' },
        { name: 'Samuel', meaning: 'Heard by God', cultural_notes: 'Timeless name with formal and casual options' },
        { name: 'David', meaning: 'Beloved', cultural_notes: 'Common across many cultures and languages' },
        { name: 'Joseph', meaning: 'God will add', cultural_notes: 'Traditional name with nickname Joe' },
        { name: 'Carter', meaning: 'Transporter of goods', cultural_notes: 'Modern professional sound' },
        { name: 'Owen', meaning: 'Young warrior', cultural_notes: 'Short and distinctive' },
        { name: 'Wyatt', meaning: 'Brave in war', cultural_notes: 'Strong Western associations' },
        { name: 'John', meaning: 'God is gracious', cultural_notes: 'One of the most classic male names globally' },
        { name: 'Jack', meaning: 'God is gracious', cultural_notes: 'Friendly, approachable sound' },
        { name: 'Luke', meaning: 'Light-giving', cultural_notes: 'Short, easy to pronounce internationally' },
        { name: 'Gabriel', meaning: 'God is my strength', cultural_notes: 'Works well across cultures' },
        { name: 'Anthony', meaning: 'Priceless one', cultural_notes: 'Classic with Italian heritage' },
        { name: 'Isaac', meaning: 'Laughter', cultural_notes: 'Biblical name with positive connotation' },
        { name: 'Grayson', meaning: 'Son of the steward', cultural_notes: 'Modern with professional sound' },
        { name: 'Julian', meaning: 'Youthful', cultural_notes: 'Works well in multiple languages' },
        { name: 'Lincoln', meaning: 'Lake colony', cultural_notes: 'Presidential associations' }
    ],
    female: [
        { name: 'Emma', meaning: 'Universal, whole', cultural_notes: 'Elegant and easy to pronounce' },
        { name: 'Sophia', meaning: 'Wisdom', cultural_notes: 'International appeal' },
        { name: 'Olivia', meaning: 'Peace, olive tree', cultural_notes: 'Modern and sophisticated' },
        { name: 'Ava', meaning: 'Life, living one', cultural_notes: 'Short and internationally friendly' },
        { name: 'Isabella', meaning: 'Devoted to God', cultural_notes: 'Romantic sound with nickname options' },
        { name: 'Mia', meaning: 'Mine, beloved', cultural_notes: 'Short and works in many languages' },
        { name: 'Charlotte', meaning: 'Free woman', cultural_notes: 'Royal associations with classic appeal' },
        { name: 'Amelia', meaning: 'Work', cultural_notes: 'Vintage name with modern popularity' },
        { name: 'Harper', meaning: 'Harp player', cultural_notes: 'Modern unisex name gaining popularity' },
        { name: 'Evelyn', meaning: 'Wished for child', cultural_notes: 'Elegant with vintage charm' },
        { name: 'Abigail', meaning: 'Fathers joy', cultural_notes: 'Biblical name with classic appeal' },
        { name: 'Emily', meaning: 'Industrious, striving', cultural_notes: 'Timeless name recognized globally' },
        { name: 'Elizabeth', meaning: 'God is my oath', cultural_notes: 'Royal name with many nickname options' },
        { name: 'Sofia', meaning: 'Wisdom', cultural_notes: 'Alternative spelling that works in many cultures' },
        { name: 'Avery', meaning: 'Ruler of elves', cultural_notes: 'Modern unisex name with professional sound' },
        { name: 'Ella', meaning: 'Fairy maiden', cultural_notes: 'Short and musical sound' },
        { name: 'Madison', meaning: 'Son of Matthew', cultural_notes: 'Modern name with professional sound' },
        { name: 'Scarlett', meaning: 'Red', cultural_notes: 'Vibrant name with literary connections' },
        { name: 'Victoria', meaning: 'Victory', cultural_notes: 'Royal associations and works internationally' },
        { name: 'Aria', meaning: 'Air, song', cultural_notes: 'Musical name with cross-cultural appeal' },
        { name: 'Grace', meaning: 'Elegance, divine favor', cultural_notes: 'Virtue name with positive connotations' },
        { name: 'Chloe', meaning: 'Blooming', cultural_notes: 'Fresh sound that works internationally' },
        { name: 'Penelope', meaning: 'Weaver', cultural_notes: 'Classic with modern revival' },
        { name: 'Layla', meaning: 'Night', cultural_notes: 'Arabic origin with musical associations' },
        { name: 'Riley', meaning: 'Valiant', cultural_notes: 'Modern unisex name with friendly sound' },
        { name: 'Zoe', meaning: 'Life', cultural_notes: 'Short, vibrant name that works internationally' },
        { name: 'Nora', meaning: 'Honor', cultural_notes: 'Simple, elegant with vintage appeal' },
        { name: 'Lily', meaning: 'Pure', cultural_notes: 'Floral name with delicate image' },
        { name: 'Eleanor', meaning: 'Bright, shining one', cultural_notes: 'Classic name with historical significance' },
        { name: 'Hannah', meaning: 'Grace', cultural_notes: 'Biblical name that works across cultures' },
        { name: 'Lillian', meaning: 'Lily flower', cultural_notes: 'Traditional with nickname options' },
        { name: 'Natalie', meaning: 'Birthday of the Lord', cultural_notes: 'Works well across multiple languages' },
        { name: 'Hazel', meaning: 'The hazelnut tree', cultural_notes: 'Nature name with vintage charm' },
        { name: 'Violet', meaning: 'Purple flower', cultural_notes: 'Victorian name with modern revival' },
        { name: 'Aurora', meaning: 'Dawn', cultural_notes: 'Mythological name with natural beauty' }
    ]
};